### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Alejandro-Trave-Instagram-Bootstrap#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- Muy buen trabajo @Atravep ,  ¡Felicidades! 
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- En lugar de aplicar estilos directamente a las etiquetas HTML como `<i>`, `<h3>`, `<button>`,... recuerda que puedes usar clases CSS para un mejor mantenimiento y reutilización de estilos.
- Muy buen proyecto.

**Comment by Atravep** [comment]
Gracias, Eduardo!!

**Comment by EduardoHernandezGuzman** [comment]
Muy buen proyecto... A por el siguiente!!!
